# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w1ab2c21c45c15c15
# Amazon EC2 instance in a security group Creates an Amazon EC2 instance in an Amazon EC2 security group.
---
AWSTemplateFormatVersion: "2010-09-09"
Description:
  "AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample:
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a stack
  from this template."
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 10.0.0.0/8
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VPC:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-347a7953
  SubnetId:
    Description: Subnet (Select Internal)
    Type: AWS::EC2::Subnet::Id
    Default: subnet-645e2f3f

Resources:
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: CSG-CWF-EKS-SERVICE-ROLE
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - eks.amazonaws.com
                - ec2.amazonaws.com
              AWS:
                - "arn:aws:iam::911962207156:role/CSG-CWF-JENKINS-EC2Role-1B8PFGEI04BEZ"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::911962207156:policy/CSG-CustomKMSPolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      Policies:
        - PolicyName: ConsolidatedPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "ec2:*"
                  - "eks:*"
                  - "ecs:*"
                  - "ecr:*"
                  - "s3:*"
                  - "lambda:*"
                  - "cloudformation:*"
                  - "codecommit:*"
                  - "codepipeline:*"
                Resource:
                  - "*"
        # - PolicyName: AssumeRolePolicyDocument
        #   PolicyDocument:
        #     Version: "2012-10-17"
        #     Statement:
        #       - Effect: Allow
        #         Action: sts:AssumeRole
        #         Resource:
        #           - "arn:aws:iam::911962207156:root"
        # - PolicyName: AssumeRolePolicyDocument
        #   PolicyDocument:
        #     Version: "2012-10-17"
        #     Statement:
        #       - Effect: Allow
        #         Action: sts:AssumeRole
        #         Resource:
        #           - "arn:aws:iam::911962207156:role/CSG-CWF-JENKINS-EC2Role-1B8PFGEI04BEZ"
